### ISSUE TITLE
Reorder page edit widgets

### ISSUE THREAD

**Issue by xolotl** [lumenlearning/candela#100]
The new Edit Navigation Links widget is super-useful, but falls below the fold so one has to scroll to it. We recommend reordering the widgets as per this image:
![edit_page_ _authoring_guide_ _pressbooks](https://cloud.githubusercontent.com/assets/997548/9239590/29b7c3f8-4112-11e5-9e3f-315d2c00feaf.png)

**Comment by bracken** [comment]
I just found out you can drag those around yourself and it'll remember it. :)
