### ISSUE TITLE
some Candela pages don't fully load in Bb via LTI

### ISSUE THREAD

**Issue by xolotl** [lumenlearning/candela#38]
Some of the links made via this ThinCC don't fully load in Bb (eg, note missing left/right nav and content).
![blackboard_learn](https://cloud.githubusercontent.com/assets/997548/7632395/71566c94-fa01-11e4-84c4-dee544a44ff8.png)

I will post the related ThinCC to Slack #dev referencing this issue.

Unfortunately, I need the Bb shell to make a working demo, so I'll be modifying it. but the Candela course at issue here is:
https://courses.candelalearning.com/biology11xdemo/

**Comment by xolotl** [comment]
Looking at the ThinCC, it appears that the LTI link was made to the part containing the page rather than the page itself.

Part: The Chemical Foundation of Life
https://courses.candelalearning.com/biology11xdemo/part/the-chemical-foundation-of-life-atoms-and-elements/

Page: Introduction
https://courses.candelalearning.com/biology11xdemo/chapter/32/

**Comment by bracken** [comment]
Fixed by: 376aea5
